cities_by_country = {
        'England': [
            'bath',
            'birmingham',
            'bradford',
            'brighton and hove',
            'bristol',
            'cambridge',
            'canterbury',
            'carlisle',
            'chester',
            'chichester',
            'coventry',
            'derby',
            'durham',
            'ely',
            'exeter',
            'gloucester',
            'hereford',
            'kingston upon hull',
            'lancaster',
            'leeds',
            'leicester',
            'lichfield',
            'lincoln',
            'liverpool',
            'city of london',
            'london',
            'manchester',
            'newcastle upon tyne',
            'newcastle',
            'norwich',
            'nottingham',
            'oxford',
            'peterborough',
            'plymouth',
            'portsmouth',
            'preston',
            'ripon',
            'salford',
            'salisbury',
            'sheffield',
            'southampton',
            'st albans',
            'st. albans',
            'stoke-on-trent',
            'stoke on trent',
            'sunderland',
            'truro',
            'wakefield',
            'wells',
            'westminster',
            'winchester',
            'wolverhampton',
            'worcester',
            'york',
        ],
        'Wales': [
            'bangor',
            'cardiff',
            'newport',
            'st davids',
            'swansea',
        ],
        'Scotland': [
            'aberdeen',
            'dundee',
            'edinburgh',
            'glasgow',
            'inverness',
            'stirling',
        ],
        'Northern Ireland': [
            'aberdeen',
            'dundee',
            'edinburgh',
            'glasgow',
            'inverness',
            'stirling',
        ],
        'Ireland': [
            'cork',
            'waterford',
            'kilkenny',
            'limerick',
            'galway',
            'dublin',
            'armagh',
            'belfast',
            'londonderry',
            'derry',
            'lisburn',
            'newry',   
        ]
    }

all_cities = cities_by_country['England'] + cities_by_country['Wales'] + cities_by_country['Scotland'] + cities_by_country['Northern Ireland'] + cities_by_country['Ireland']