# Generated by Django 2.2 on 2019-05-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190507_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
