# Generated by Django 2.2 on 2019-05-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190430_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='zipcode',
            new_name='postcode',
        ),
    ]
