# Generated by Django 2.2 on 2019-05-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_auto_20190506_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='message',
            field=models.TextField(default='x'),
            preserve_default=False,
        ),
    ]
