# Generated by Django 2.2 on 2019-05-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_auto_20190508_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='user_group',
            field=models.CharField(max_length=20),
        ),
    ]
