# Generated by Django 2.2 on 2019-05-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
