# Generated by Django 2.2 on 2019-05-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_enquiry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='searched_bedrooms',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='searched_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='searched_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='searched_price',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
