# Generated by Django 2.2 on 2019-05-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_auto_20190507_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='contact_date',
            new_name='message_date',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='user_group',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
