# Generated by Django 2.2 on 2019-05-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_auto_20190508_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='response_to_user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
