# Generated by Django 2.2 on 2019-08-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingmessages',
            name='selfie',
            field=models.ImageField(blank=True, upload_to='photos/shibas_mehndi_selfies/'),
        ),
    ]
